# Generated by Django 5.2 on 2025-04-28 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('jogos_favoritos', models.TextField()),
                ('streamers_favoritos', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoIdentidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documentos/')),
                ('dados_extraidos', models.JSONField(blank=True, null=True)),
                ('validado', models.BooleanField(default=False)),
                ('fan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fans.fan')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEsports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('verificado', models.BooleanField(default=False)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_esports', to='fans.fan')),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('dados_extraidos', models.JSONField(blank=True, null=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='fans.fan')),
            ],
        ),
    ]
