# Generated by Django 5.2 on 2025-05-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='endereco',
            field=models.TextField(unique=True),
        ),
    ]
