# Generated by Django 5.2 on 2025-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fan',
            old_name='telefone',
            new_name='numero_whatsapp',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='jogos_favoritos',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='streamers_favoritos',
        ),
        migrations.AddField(
            model_name='fan',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fan',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fan',
            name='twitch_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fan',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentoIdentidade',
        ),
    ]
