# Generated by Django 5.2 on 2025-05-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fan',
            old_name='twitch_username',
            new_name='instagram_id',
        ),
    ]
