# Generated by Django 5.2 on 2025-04-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0002_rename_telefone_fan_numero_whatsapp_remove_fan_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='cpf',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fan',
            name='endereco',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
