# Generated by Django 5.2 on 2025-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0002_rename_twitch_username_fan_instagram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='documento_validacao',
            field=models.FileField(blank=True, null=True, upload_to='documentos/validacao/'),
        ),
        migrations.AddField(
            model_name='fan',
            name='motivo_validacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fan',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
