# Generated by Django 5.2 on 2025-04-29 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0003_fan_cpf_fan_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='jogos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='pro_players/')),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='streamers/')),
            ],
        ),
        migrations.RemoveField(
            model_name='redesocial',
            name='fan',
        ),
        migrations.CreateModel(
            name='PreferenciasFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fans.fan')),
                ('jogos', models.ManyToManyField(blank=True, to='fans.jogo')),
                ('pro_players', models.ManyToManyField(blank=True, to='fans.proplayer')),
                ('streamers', models.ManyToManyField(blank=True, to='fans.streamer')),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilEsports',
        ),
        migrations.DeleteModel(
            name='RedeSocial',
        ),
    ]
