# Generated by Django 5.2 on 2025-05-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fans', '0004_jogo_proplayer_streamer_remove_redesocial_fan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='preferenciasfan',
            name='jogos',
        ),
        migrations.RemoveField(
            model_name='preferenciasfan',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='preferenciasfan',
            name='pro_players',
        ),
        migrations.RemoveField(
            model_name='preferenciasfan',
            name='streamers',
        ),
        migrations.CreateModel(
            name='PerfilEsports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('verificado', models.BooleanField(default=False)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_esports', to='fans.fan')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='preferences/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='fans.preferencetopic')),
            ],
            options={
                'ordering': ['topic', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('dados_extraidos', models.JSONField(blank=True, null=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociais', to='fans.fan')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fans.preferenceoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'option')},
            },
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='ProPlayer',
        ),
        migrations.DeleteModel(
            name='PreferenciasFan',
        ),
        migrations.DeleteModel(
            name='Streamer',
        ),
    ]
